Feature/7 setup project
modous/Portfolio pull request #9
Opened 2024-04-04 13:13 UTC by modous

https://github.com/users/modous/projects/7/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C87257315%2C87257317%2C87257316%2C87257318%2C%22Labels%22%5D&pane=issue&itemId=58360504

Finished setting up the project

2024-04-05 17:33 UTC, MokhtarAkle requested changes
Code ziet er netjes uit, voeg nog even een .gitignore toe voor de node_modules map en .env

2024-04-05 17:33 UTC, MokhtarAkle commented on views/index.ejs
Maak gebruik van de `<main>` tag voor semantisch correcte HTML

2024-04-05 17:33 UTC, MokhtarAkle commented on views/partials/foot.ejs
`body` en `html` tags worden hier gesloten maar zijn nergens geopend

2024-04-05 17:33 UTC, MokhtarAkle commented on views/partials/head.ejs
Probeer `<script>` die iets renderen onderaan de pagina te zetten om performance te verbeteren.

2024-04-05 17:33 UTC, MokhtarAkle commented on index.js
> +const { AwesomeGraphQLClient } = require("awesome-graphql-client");
Zorg ervoor dat je de keuze van een alternatieve graphql client kan onderbouwen.

2024-04-05 17:33 UTC, MokhtarAkle commented on .env
dit hoort in je .gitignore

2024-04-06 14:31 UTC, modous commented on views/partials/foot.ejs
deze worden geopend in de head.ejs partial file

2024-04-06 14:41 UTC, merged